import turtle

turtle.screensize(800, 600, 'white')
turtle.pensize(3)
# tuple.title('海绵宝宝')
turtle.speed(18)

def go_to(x, y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()

go_to(0, 0)

def head():
    go_to(-200, 180)
    turtle.fillcolor('pink')
    turtle.begin_fill()
    turtle.seth(-30)
    for _ in range(6):
        turtle.circle(36, 60)
        turtle.circle(-36, 60)
    turtle.seth(-125)
    for _ in range(5):
        turtle.circle(40,60)
        turtle.circle(-40,60)
    turtle.seth(-210)
    for _ in range(4):
        turtle.circle(45,60)
        turtle.circle(-45,60)
    turtle.seth(65)
    for _ in range(5):
        turtle.circle(40,60)
        turtle.circle(-40,60)
    turtle.end_fill()

def eye():
    # 眼白
    go_to(14, -5)
    turtle.fillcolor('#f0f0f0')
    turtle.begin_fill()
    turtle.circle(65, 360)
    turtle.end_fill()
    turtle.begin_fill()
    go_to(13,12)
    turtle.seth(98)
    turtle.circle(-65,360)
    turtle.end_fill()

    #眼球
    go_to(-10,20)
    turtle.fillcolor('blue')
    turtle.begin_fill()
    turtle.circle(20,360)
    turtle.end_fill()
    go_to(-22,20)
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(7,360)
    turtle.end_fill()
    go_to(40,15)
    turtle.fillcolor('blue')
    turtle.begin_fill()
    turtle.circle(-20, 360)
    turtle.end_fill()
    go_to(53,15)
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(-7,360)
    turtle.end_fill()

    #睫毛
    go_to(-95,65)
    turtle.left(20)
    turtle.forward(40)
    go_to(-50,87)
    turtle.right(25)
    turtle.forward(32)
    go_to(0,70)
    turtle.right(25)
    turtle.forward(40)

    go_to(40, 75)
    turtle.left(35)
    turtle.forward(40)
    go_to(90, 87)
    turtle.right(18)
    turtle.forward(30)
    go_to(120, 70)
    turtle.right(25)
    turtle.forward(40)

def nose():
    turtle.fillcolor('pink')
    go_to(0, -7)
    turtle.begin_fill()
    turtle.right(50)
    turtle.circle(-60, 30)
    turtle.color('pink')
    turtle.goto(15,-40)
    turtle.end_fill()
    turtle.color('black')
    go_to(0, -7)
    turtle.seth(-75)
    turtle.forward(30)
    go_to(30,-7)
    turtle.seth(-105)
    turtle.forward(30)

    go_to(-120, - 60)
    turtle.seth(-45)
    turtle.circle(200, 30)
    turtle.seth(0)
    turtle.forward(100)
    turtle.seth(15)
    turtle.circle(200, 30)

def tooth():
    go_to(-30,-114)
    turtle.seth(-95)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.forward(30)
    turtle.seth(0)
    turtle.forward(40)
    turtle.seth(95)
    turtle.forward(30)
    go_to(-30,-114)
    turtle.end_fill()

    go_to(30, -114)
    turtle.seth(-95)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.forward(30)
    turtle.seth(0)
    turtle.forward(40)
    turtle.seth(95)
    turtle.forward(30)
    go_to(60, -114)
    turtle.end_fill()

def body():
    go_to(-170,-180)
    turtle.seth(-120)
    turtle.circle(150, 30)
    turtle.seth(0)
    turtle.forward(40)
    turtle.seth(100)
    turtle.forward(35)
    turtle.seth(-80)
    turtle.forward(100)
    turtle.fillcolor('brown')
    turtle.begin_fill()
    turtle.seth(0)
    turtle.forward(300)
    turtle.seth(80)
    turtle.forward(110)
    turtle.seth(-100)
    turtle.forward(65)
    turtle.seth(180)
    turtle.forward(315)
    go_to(-118,-400)
    turtle.end_fill()
    go_to(-170,-255)
    turtle.fillcolor('yellow')
    turtle.begin_fill()
    turtle.seth(-75)
    turtle.forward(80)
    turtle.seth(0)
    turtle.forward(17)
    turtle.seth(105)
    turtle.forward(85)
    turtle.end_fill()

    go_to(200, -170)
    turtle.seth(-60)
    turtle.circle(-150,30)
    turtle.seth(-180)
    turtle.forward(45)
    turtle.begin_fill()
    turtle.seth(0)
    turtle.forward(20)
    turtle.seth(-100)
    turtle.forward(85)
    turtle.seth(180)
    turtle.forward(20)
    turtle.end_fill()

def tie():
    go_to(-50,-225)
    turtle.seth(-40)
    turtle.forward(40)
    turtle.seth(30)
    turtle.forward(52)
    go_to(30,-225)
    turtle.seth(-30)
    turtle.forward(40)
    turtle.seth(40)
    turtle.forward(45)
    turtle.fillcolor('red')
    go_to(0, -240)
    turtle.begin_fill()
    turtle.seth(-60)
    turtle.forward(10)
    turtle.seth(0)
    turtle.forward(30)
    turtle.seth(60)
    turtle.forward(15)
    go_to(30,-225)
    turtle.end_fill()
    go_to(4,-250)
    turtle.begin_fill()
    turtle.seth(-100)
    turtle.forward(80)
    turtle.seth(0)
    turtle.forward(55)
    turtle.seth(100)
    turtle.forward(80)
    turtle.end_fill()

head()
eye()
nose()
tooth()
body()
tie()
turtle.mainloop()